[Definition]
# Regex untuk membaca log Snort dengan format "fast" (-A fast)
# Contoh Log: 05/20-02:30:00.123456 [**] [1:9001001:1] [ArgonAuth] ICMP Ping Detected [**] [Classification: Misc activity] [Priority: 1] {ICMP} 192.168.10.20 -> 192.168.10.10
failregex = \[.*\] \[.*\] .* \{.*\} <HOST> -> .*

ignoreregex =
